### ISSUE TITLE
Error message on macOS

### ISSUE THREAD

**Issue by gene-pavlovsky** [rockandska/fzf-obc#19]
I've installed this per the instructions, but attempting to use tab completion results in this error being printed:
bash: /proc/cpuinfo: No such file or directory

There is no /proc on macOS.

The completion itself seems to be working, although with the annoying error message on every attempt to use it, I didn't do any extensive testing.

**Comment by rockandska** [comment]
Sorry, didn't had the time to test on macos but see clearly where it occurs and will push a patch before the end of the day if i can.

Thanks to have take the time to test it

**Comment by rockandska** [comment]
Could you checkout the branch `fix/sort_parallel_macosx_error` and let me know if it is ok now before merging it please ?

Regards,

**Comment by gene-pavlovsky** [comment]
Great, thank you. I will test it when you have a patch available.
I'm also wondering if there would be some more undetected issues caused by macOS.
While writing some bash scripts on macOS, I've found out that some standard commands provided by macOS have BSD-style options, different from their GNU counterparts which are more familiar to me from my previous Linux experience. When using an interactive shell I mostly avoid dealing with this, by using GNU versions of everything installed via homebrew package manager, but any shell scripts running would use the built-in tools from macOS.

**Comment by gene-pavlovsky** [comment]
Tested your branch, no more errors. Thanks for that fix.
As for how it works with gradle, I've posted a comment in the original issue in the fzf repo.

**Comment by rockandska** [comment]
thanks for the test i will merge it and release a patch version soon.

For you answer on fzf original issue, post your concerns about zfz-obc in a new issue here to not pollute the fzf issue itself :smile: 
And add some reproducible example and will take a look if i could do something if it is not a pain ^^

Thanks
