### ISSUE TITLE
Difficult to use fzf-obc with gradle

### ISSUE THREAD

**Issue by gene-pavlovsky** [rockandska/fzf-obc#23]
I was trying to use gradle with fzf-obc, but it turns out to be not so convenient due to gradle completion list containing task descriptions, not just their names. As a result, both name and description end up on the command line, which is undesirable.

To test, install gradle (I have version 6.0), [gradle-completion](https://github.com/gradle/gradle-completion), and for testing purposes create a new directory and create a build.gradle file there, with contents from [this gist](https://gist.githubusercontent.com/sit/3606537/raw/3e70be257b328a10a854cad1c37544ddb3f1a41f/build.gradle), for example.
Type `gradle <TAB>` (with fzf-obc activated), and the completion list is shown. It takes several seconds when done for the first time, after that it will work instantaneous as gradle-completion has a cache.

Here's an example item from the completion list:
`wrapper  - Generates Gradle wrapper files.`
If it's selected, the whole thing is appended to the command line, while it would be desirable to have only `wrapper` on the command line.
If it would be possible to be able to specify some post-processing step for a particular completion command, a function could be set up that strips the whitespace, the dash and the description.
Maybe it's already a feature? Or could be a new feature request. Or maybe you have better ideas?

Thanks for looking into it!

**Comment by rockandska** [comment]
I've just take a look at the gradle completion script and should be easy to implement.
Without testing it, i'm also pretty sure you will hit without fzf-obc unsuspected things if you use one of those options with a filename/directory with a space in it : `-b|--build-file|-c|--settings-file|-I|--init-script|-g|--gradle-user-home|--include-build|--project-cache-dir|--project-dir`

After looking at how it works, it should be easy to implement.
I will ping you when done

**Comment by rockandska** [comment]
If you don't mind to have the description in fzf-obc ( because i need to had a hook for this kind of purpose ), you could try to add a post function (in a same way as with sort) as the one bellow :
```
__fzf_obc_post__gradle() {
	local prev
	_get_comp_words_by_ref -n : -p prev
	case "$prev" in
		-b|--build-file|-c|--settings-file|-I|--init-script|-g|--gradle-user-home|--include-build|--project-cache-dir|--project-dir)
			return 0
			;;
		*)
			local i
			for i in "${!COMPREPLY[@]}";do
				COMPREPLY[$i]="${COMPREPLY[i]%%  *}"
			done
			return 0
			;;
	esac
}
```

**Comment by rockandska** [comment]
Did it solve your problem ?
Just merge a better documentation available [here](https://fzf-obc.readthedocs.io) and will add a new feature who will allow you to preserve the descriptions when displaying choice but will be removed when selected

Regards,

**Comment by gene-pavlovsky** [comment]
I'd like to try it out, what should I do? Add the `__fzf_obc_post__gradle` function somewhere?

**Comment by rockandska** [comment]
Hi @gene-pavlovsky ,

I add it as a 'plugin' in 1.3.0 and should work out of the box with >= 1.3.0

Feel free to post here if there is something who didn't work as expected and i will reopen this issue if needed.

Regards,

**Comment by gene-pavlovsky** [comment]
Ah, it works without any additional configuration, indeed! I just had to try it, silly me :)
The plugins are all activated by default?

**Comment by rockandska** [comment]
Yeah, all plugins (only two at this time ^^) are activated by default but could be deactivated independently if not working as expected or don't want them.

I'm not really satisfied yet with how i implemented the plugins but should not change so much

Regards,
