### ISSUE TITLE
Add prerequisites step for MacOS

### ISSUE THREAD

**Issue by timurb** [rockandska/fzf-obc#30]
MacOS has a bit different flavor of coreutils and currently fzf-obc doesn't work on MacOS.
On MacOS there are the following incompatibilities with modern linux distributions:
* sed doesn't support `-r` (I think `-E` is used instead) and `-z` options
* `head -n -1` syntax is not supported. `head -n 1` works fine (don't know if in intended way or not)
* cut doesn't support `-z` option
* shopt globstar is not supported out of the box

Probably a few more options could be unsupported — I gave up at this point.

I'm using MacOS 10.14.6 Mojave and tried to select tag 1.2.0 for installation.

**Comment by timurb** [comment]
Actually after proper installation/upgrade of bash, sed and coreutils the issue faded away:
```
brew install bash
brew install gnu-sed
brew install coreutils
echo "export PATH=/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/sbin:$PATH" >> ~/.bash_profile
chsh -s /usr/local/bin/bash
```
May be it makes sense to put that into docs.

**Comment by rockandska** [comment]
Hello,

It is already in the [docs](https://fzf-obc.readthedocs.io/en/1.2.0/prerequisites/) more or less explicitly but could add a specific section/warning/step for MacOS user.

Thanks for your feedback

**Comment by rockandska** [comment]
Added to [prerequisites section](https://fzf-obc.readthedocs.io/en/latest/prerequisites/)
