### ISSUE TITLE
Pathname completion opens fzf when not needed

### ISSUE THREAD

**Issue by gene-pavlovsky** [rockandska/fzf-obc#36]
My `~/.config` contains only a few things, and `fzf-obc` is the only item starting with `f`.

Type `cd ~/.config/f` <TAB>
Expected: completes to `cd ~/.config/fzf-obc/` (default bash completion does so)
Actual: fzf is triggered, displaying 2/2 results, one is fzf-obc/, one is an empty line (selecting that results in `cd ~/.config/f/` which does not exist)

Same issue when trying to `ls ~/.bashr` <TAB> (expected `.bashrc`, actual 2/2 results, one is `.bashrc`, one is an empty line - selecting that one results in `~/.bashr/`).

macOS, bash 5.0.11 from homebrew, latest git version of fzf-obc (1.3.0)

**Comment by rockandska** [comment]
Hi @gene-pavlovsky 

I didn't try yet with bash 5.0 but I will in a few days because I can't think what could cause this and don't have this behavior with bash 4.x

For later issue, please try to provide a reproducible example of the behavior you encounter to be able to reproduce easily, it will help me a lot.

Regards

**Comment by rockandska** [comment]
In fact I'm able to reproduce it and should add more (more,more,more) CI tests because its seems that happen only when there is only one choice available.

I will get you in touch

Sorry for the incoveniance

**Comment by gene-pavlovsky** [comment]
Yes it happens when there is only one choice so in theory it should just fully complete the thing

**Comment by gene-pavlovsky** [comment]
Thanks, seems to work fine now

**Comment by rockandska** [comment]
Glad to hear it, sorry for the delay
