### ISSUE TITLE
Everything on the left of the cursor is erased after selecting completion candidate

### ISSUE THREAD

**Issue by EgorDuplensky** [rockandska/fzf-obc#40]
For example i have something like this before the cursor (_fzf-obc[master]_ is a prompt in this case):
`fzf-obc[master]: git sta|`
And after **status** is selected the result is just:
`tus` |
And when Enter being hit the correct **git status** command is executed.
The problem is reproduced without any bashrc except sourcing bash_completion.

**Comment by EgorDuplensky** [comment]
<details><summary>Gif</summary>
![gif](https://s8.gifyu.com/images/gifcast_200910204746.gif)
</details>

**Comment by rockandska** [comment]
Hi,

Does this behaviour is reproducible by executing this ?

```shell
echo -e "stage\nstash\nstatus" | fzf-tmux --height 40% --reverse
``` 

Does this behaviour is reproducible doing the same thing in a clean env ?

```shell
env -i PATH="${PATH}" bash --norc --noprofile
source /etc/bash_completion
source [path-to-fzf-obc]/bin/fzf-obc
```

Regards,

**Comment by EgorDuplensky** [comment]
Yes, it is reproducible with clean env.
Actually it seems that problem exists only with suckless st terminal.
xfce4-terminal has no such issue. And somehow i missed that fzf itself has the same issue when running from st.
So i think the issue can be closed (any help with understanding why st has this issue is very appreciated :) )

**Comment by rockandska** [comment]
This behaviour need to be address directly to st who doesn't support `redraw-current-line` (cf this topic on [reddit])(https://www.reddit.com/r/suckless/comments/f9saa1/bind_e0n_in_st/)

**Comment by EgorDuplensky** [comment]
Thank you.
Have to drop st to use your package.
