### ISSUE TITLE
Add support for readline completion

### ISSUE THREAD

**Issue by kshitij-jo** [rockandska/fzf-obc#51]
Thank you for you this amazing tool!

Addition of readline completion would allow for an even more pleasant experience.
fzf-tab-completion (https://github.com/lincheney/fzf-tab-completion) is a great tool, but lacks the customizablility fzf-obc provides. However it has readline completion which is very useful.

If possible, please consider adding similar functionality to fzf-obc.

**Comment by rockandska** [comment]
> Thank you for you this amazing tool!
Thanks

> If possible, please consider adding similar functionality to fzf-obc.

Sadly, it is not possible to implement something as @lincheney does (catch readline completion in python, etc..).
It does not work at the same level.
fzf-obc works at the completion level (by wrapping completion scripts), while fzf-tab-completion works at the readline library level by catching call to the function who show completion.
Additionally, even if I love fzf-tab-completion, it only works for programs who have not readline statically linked.

Regards,
